# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon = false

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_api_version=0.152.2+26.2
#Following modifiers are accepted: compileOnly, runtime

lithium_version=mc26.2-0.25.1-fabric

compileOnly.iris_version=1.11.2+26.2-fabric
compileOnly.modmenu_version=20.0.0

chunky_version=DCgX52a5
vivecraft_version=26.2-1.3.12-fabric
flashback_version=VaqZB1DF


# Mod Properties
mod_version = 0.2.20-beta
maven_group = me.cortex
archives_base_name = voxy
